services:
  echo_web:
    build:
      context: .
      dockerfile: Dockerfile
    image: myapp
    ports:
      - "8080:8080"
    environment:
      APP_ENV: "production"
      PORT: "8080"
    restart: unless-stopped